quarkus.http.port=8080
quarkus.application.name=document-service


# gRPC Configuration
quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.enable-plain-text=true
quarkus.grpc.server.enable-ssl=false
quarkus.grpc.auth.enabled=true
quarkus.grpc.server.use-separate-server=false



#Configure db
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = admin
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/my_database
%docker.quarkus.datasource.jdbc.url = jdbc:postgresql://host.docker.internal:5432/my_database
quarkus.hibernate-orm.database.generation = update

%test.quarkus.datasource.db-kind = h2
%test.quarkus.datasource.jdbc.url = jdbc:h2:mem:testdb
%test.quarkus.datasource.username = sa
%test.quarkus.datasource.password = sa
%test.quarkus.hibernate-orm.database.generation = update
%test.quarkus.hibernate-orm.log.sql = true
%test.quarkus.hibernate-orm.log.bind-param = true

document.storage.type=redis
# Configure the base URL for the client
#document-caching/mp-rest/url=http://localhost:8082
#document-caching/mp-rest/connectTimeout=1000
#document-caching/mp-rest/readTimeout=5000

quarkus.grpc.clients.document-caching.host=localhost
%docker.quarkus.grpc.clients.document-caching.host=host.docker.internal
quarkus.grpc.clients.document-caching.port=8082
quarkus.grpc.clients.document-caching.plain-text=true

quarkus.container-image.build=true
quarkus.container-image.name=document-service
quarkus.container-image.group=sagargrovetech

consul.host=localhost
%docker.consul.host=host.docker.internal
consul.port=8500

quarkus.stork.document-caching.service-discovery.type=consul
quarkus.stork.document-caching.service-discovery.consul-host=localhost
%docker.quarkus.stork.document-caching.service-discovery.consul-host=host.docker.internal
quarkus.stork.document-caching.service-discovery.consul-port=8500
quarkus.grpc.clients.document-caching.stork.enabled=true
quarkus.smallrye-health.root-path=/q/health