
# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/realms/secure-docs
quarkus.oidc.client-id=secure-docs-client
quarkus.oidc.credentials.secret=0w39aIdj7RloFBLqWrIxqGXOZ8HrO1O7
quarkus.oidc.token-issuer=http://localhost:8180/realms/secure-docs


# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true

# gRPC Configuration
quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.enable-plain-text=true
quarkus.grpc.server.enable-ssl=false
quarkus.grpc.auth.enabled=true
quarkus.grpc.server.use-separate-server=false



# Enable debug logging for security
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.http.auth.proactive=true

quarkus.oidc.token.audience-check.enabled=true
quarkus.grpc.server.security.enabled=true


quarkus.analytics.disabled=false
