quarkus.http.port=8080

# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/realms/secure-docs
quarkus.oidc.client-id=secure-docs-client
quarkus.oidc.credentials.secret=0w39aIdj7RloFBLqWrIxqGXOZ8HrO1O7
quarkus.oidc.token-issuer=http://localhost:8180/realms/secure-docs


# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true

# gRPC Configuration
quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.enable-plain-text=true
quarkus.grpc.server.enable-ssl=false
quarkus.grpc.auth.enabled=true
quarkus.grpc.server.use-separate-server=false



# Enable debug logging for security
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.http.auth.proactive=true

quarkus.oidc.token.audience-check.enabled=true
quarkus.grpc.server.security.enabled=true
quarkus.analytics.disabled=false

#Configure db
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = admin
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/my_database
quarkus.hibernate-orm.database.generation = update

%test.quarkus.datasource.db-kind = h2
%test.quarkus.datasource.jdbc.url = jdbc:h2:mem:testdb
%test.quarkus.datasource.username = sa
%test.quarkus.datasource.password = sa
%test.quarkus.hibernate-orm.database.generation = update
%test.quarkus.hibernate-orm.log.sql = true
%test.quarkus.hibernate-orm.log.bind-param = true

document.storage.type=db
# Configure the base URL for the client
#document-caching/mp-rest/url=http://localhost:8082
#document-caching/mp-rest/connectTimeout=1000
#document-caching/mp-rest/readTimeout=5000

quarkus.rest-client.document-caching.url=http://localhost:8082
quarkus.rest-client.document-caching.scope=jakarta.inject.Singleton
